/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: ccabde25-5001-40ba-8d44-c7075fbccacd

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

def karatsuba_n1 (n : ℤ) (b m : ℕ) : ℤ :=
  n / (b ^ m)

def karatsuba_n0 (n : ℤ) (b m : ℕ) : ℤ :=
  n % (b ^ m)

def digits (b : ℕ) (x : ℤ) : ℕ :=
  (b.digits (Int.natAbs x)).length

lemma digits_mod_le' (b m : ℕ) (x : ℤ) (hb : 1 < b) : digits b (x % (b ^ m)) ≤ m := by
  -- By definition of modulo, we know that $x \mod b^m$ is less than $b^m$.
  have h_mod_lt : Int.natAbs (x % (b^m)) < b^m := by
    exact Int.natAbs_lt_natAbs_of_nonneg_of_lt ( Int.emod_nonneg _ ( by positivity ) ) ( Int.emod_lt_of_pos _ ( by positivity ) ) |> LT.lt.trans_le <| by norm_num;
  by_cases h : x % b ^ m = 0 <;> simp_all +decide [ digits ];
  · cases h ; aesop;
  · have := @Nat.digits_len b ( Int.natAbs ( x % b ^ m ) );
    exact this hb ( by aesop ) ▸ Nat.log_lt_of_lt_pow ( by aesop ) h_mod_lt

#eval ((-12 : Int) / 4, (-12 : Int) % 4)

lemma digits_div_le'
(b m : ℕ) (x : ℤ) (hb : 1 < b) (hm : m ≠ 0) : digits b (x / (b ^ m)) ≤ (digits b x) - m + 1 := by
  -- By definition of `digits`, we know that `digits b x = length of the list of digits of `x` in base `b`.
  -- If $x \neq 0$, then $|x / b^m| \leq |x| / b^m < b^{digits b x - m + 1}$.
  have h_abs : |x / b ^ m| < b ^ (digits b x - m + 1) := by
    -- Since $|x| < b^{digits b x}$, we have $|x / b^m| \leq |x| / b^m < b^{digits b x - m}$.
    have h_abs : |x| < b ^ (digits b x) := by
      have h_abs : Int.natAbs x < b ^ (Nat.digits b (Int.natAbs x)).length := by
        exact?;
      simpa [ ← Int.ofNat_lt, Int.natAbs_abs ] using h_abs;
    by_cases h : digits b x ≤ m <;> simp_all +decide [ pow_add, pow_one, pow_mul ];
    · rw [ abs_lt ] at *;
      constructor <;> nlinarith [ pow_pos ( by positivity : 0 < ( b : ℤ ) ) m, pow_le_pow_right₀ ( by linarith : 1 ≤ ( b : ℤ ) ) h, Int.ediv_add_emod x ( b ^ m ), Int.emod_nonneg x ( by positivity : ( b ^ m : ℤ ) ≠ 0 ), Int.emod_lt_of_pos x ( by positivity : ( b ^ m : ℤ ) > 0 ) ];
    · rw [ abs_lt ] at *;
      rw [ show ( b : ℤ ) ^ digits b x = ( b : ℤ ) ^ ( digits b x - m ) * ( b : ℤ ) ^ m by rw [ ← pow_add, Nat.sub_add_cancel h.le ] ] at * ; exact ⟨ by nlinarith [ pow_pos ( by positivity : 0 < ( b : ℤ ) ) m, pow_pos ( by positivity : 0 < ( b : ℤ ) ) ( digits b x - m ), Int.ediv_add_emod x ( b ^ m ), Int.emod_nonneg x ( by positivity : ( b ^ m : ℤ ) ≠ 0 ), Int.emod_lt_of_pos x ( by positivity : ( b ^ m : ℤ ) > 0 ) ], by nlinarith [ pow_pos ( by positivity : 0 < ( b : ℤ ) ) m, pow_pos ( by positivity : 0 < ( b : ℤ ) ) ( digits b x - m ), Int.ediv_add_emod x ( b ^ m ), Int.emod_nonneg x ( by positivity : ( b ^ m : ℤ ) ≠ 0 ), Int.emod_lt_of_pos x ( by positivity : ( b ^ m : ℤ ) > 0 ) ] ⟩ ;
  -- Since $|x / b^m| < b^{digits b x - m + 1}$, the number of digits of $x / b^m$ is at most $digits b x - m + 1$.
  have h_digits_le : ∀ y : ℤ, |y| < b ^ (digits b x - m + 1) → digits b y ≤ digits b x - m + 1 := by
    intros y hy
    have h_digits_le : (Nat.digits b (Int.natAbs y)).length ≤ digits b x - m + 1 := by
      have := @Nat.digits_len b ( Int.natAbs y );
      exact if h : Int.natAbs y = 0 then by simp +decide [ h ] else by rw [ this hb h ] ; exact Nat.log_lt_of_lt_pow ( by positivity ) ( by linarith [ abs_lt.mp hy ] ) ;
    exact h_digits_le;
  exact h_digits_le _ h_abs

lemma digits_add_le' (b : ℕ) (x y : ℤ) (hb : 1 < b) : digits b (x + y) ≤ max (digits b x) (digits b y) + 1 := by
  unfold digits;
  by_cases hx : x + y = 0 <;> by_cases hy : y = 0 <;> by_cases hx' : x = 0 <;> simp_all +decide [ Nat.digits_len ];
  refine' Nat.le_of_lt_succ ( Nat.log_lt_of_lt_pow _ _ );
  · positivity;
  · -- Since $|x + y| \leq |x| + |y|$, we have $|x + y| < b^{max(log_b |x|, log_b |y|) + 1}$.
    have h_abs : Int.natAbs (x + y) < b ^ (max (Nat.log b x.natAbs) (Nat.log b y.natAbs) + 1) + b ^ (max (Nat.log b x.natAbs) (Nat.log b y.natAbs) + 1) := by
      have h_abs : Int.natAbs (x + y) ≤ Int.natAbs x + Int.natAbs y := by
        exact Int.natAbs_add_le _ _;
      exact lt_of_le_of_lt h_abs ( add_lt_add ( Nat.lt_pow_succ_log_self hb _ |> lt_of_lt_of_le <| Nat.pow_le_pow_right hb.le <| Nat.succ_le_succ <| le_max_left _ _ ) ( Nat.lt_pow_succ_log_self hb _ |> lt_of_lt_of_le <| Nat.pow_le_pow_right hb.le <| Nat.succ_le_succ <| le_max_right _ _ ) );
    rw [ pow_succ' ] ; nlinarith [ pow_pos ( zero_lt_one.trans hb ) ( Max.max ( Nat.log b x.natAbs ) ( Nat.log b y.natAbs ) + 1 ) ] ;

lemma nat_div_two_lt' (n : ℕ) (h : 1 < n) : (n + 1) / 2 < n := by
  -- Since $n > 1$, we have $n + 1 < 2n$, thus $(n + 1) / 2 < n$ by dividing both sides by 2.
  linarith [Nat.div_mul_le_self (n + 1) 2]

lemma karatsuba_step_bound_z3' (b n m : ℕ) (x : ℤ) (hb : 1 < b) (h_digits : digits b x ≤ n) (h_n : 4 < n) (h_m : m = (n + 1) / 2) : digits b (karatsuba_n1 x b m + karatsuba_n0 x b m) < n := by
  -- Let's calculate the length of the digits of $n1 + n0$.
  have h_len : digits b (karatsuba_n1 x b m + karatsuba_n0 x b m) ≤ max (digits b (karatsuba_n1 x b m)) (digits b (karatsuba_n0 x b m)) + 1 := by
    apply digits_add_le'; assumption;
  -- Since $n1$ and $n0$ are parts of $x$, their digit lengths are less than or equal to $n$.
  have h_n1_len : digits b (karatsuba_n1 x b m) ≤ n - m + 1 := by
    apply le_trans (digits_div_le' b m x hb (by
    omega)) (by
    exact Nat.succ_le_succ ( Nat.sub_le_sub_right h_digits _ ))
  have h_n0_len : digits b (karatsuba_n0 x b m) ≤ m := by
    apply digits_mod_le' b m x hb;
  omega

lemma karatsuba_step_bound_z0' (b n m : ℕ) (x : ℤ) (hb : 1 < b) (h_n : 4 < n) (h_m : m = (n + 1) / 2) : digits b (karatsuba_n0 x b m) < n := by
  -- Apply the lemma `digits_mod_le` with `x % (b ^ m)` as the argument.
  have h_digits_n0 : digits b (x % (b ^ m)) ≤ m := by
    exact digits_mod_le' b m x hb;
  -- Since $m = \frac{n + 1}{2}$ and $n > 4$, we have $m < n$.
  have h_m_lt_n : m < n := by
    omega
  exact lt_of_le_of_lt h_digits_n0 h_m_lt_n

lemma karatsuba_step_bound_z2' (b n m : ℕ) (x : ℤ) (hb : 1 < b) (h_digits : digits b x ≤ n) (h_n : 4 < n) (h_m : m = (n + 1) / 2) : digits b (karatsuba_n1 x b m) < n := by
  -- Apply the lemma digits_div_le with the given conditions.
  have h_div_le : digits b (x / (b ^ m)) ≤ (digits b x) - m + 1 := by
    convert digits_div_le' b m x hb ( by linarith [ Nat.div_add_mod ( n + 1 ) 2, Nat.mod_lt ( n + 1 ) two_pos ] ) using 1;
  -- Substitute the bounds on digits b x and m into the inequality.
  have h_subst : digits b (x / (b ^ m)) ≤ n - ((n + 1) / 2) + 1 := by
    exact h_div_le.trans ( by rw [ h_m ] ; gcongr );
  exact lt_of_le_of_lt h_subst ( by omega )

def karatsuba (x y : ℤ) (b : ℕ) (hb : 1 < b) :=
  if (max (digits b x) (digits b y)) ≤ 4 then
    x * y
  else
    let n := max (digits b x) (digits b y)
    let m  := ((n + 1) / 2)
    let z0 := (karatsuba (karatsuba_n0 x b m)
                                   (karatsuba_n0 y b m)
                                   b hb) -- floor division
    let z2 := (karatsuba (karatsuba_n1 x b m)
                                   (karatsuba_n1 y b m)
                                   b hb)
    let z3 := (karatsuba ((karatsuba_n1 x b m) + (karatsuba_n0 x b m))
                                   ((karatsuba_n1 y b m)  + (karatsuba_n0 y b m))
                                   b hb)
    z2 * (b ^ (2 * m)) + (z3 - z2 - z0) * (b ^ m) + z0
termination_by
  max (digits b x) (digits b y)
decreasing_by
  -- Apply the lemma `karatsuba_step_bound_z0'` to both `x` and `y`.
  have h_x : digits b (karatsuba_n0 x b ((Max.max (digits b x) (digits b y) + 1) / 2)) < Max.max (digits b x) (digits b y) := by
    apply karatsuba_step_bound_z0'; assumption; linarith; rfl
  have h_y : digits b (karatsuba_n0 y b ((Max.max (digits b x) (digits b y) + 1) / 2)) < Max.max (digits b x) (digits b y) := by
    -- Apply the lemma `karatsuba_step_bound_z0'` to `y`.
    apply karatsuba_step_bound_z0' b (max (digits b x) (digits b y)) ((max (digits b x) (digits b y) + 1) / 2) y hb (by linarith) rfl;
  exact max_lt h_x h_y; (
  -- Apply the lemmas to both x and y to show that their high parts have fewer digits than n.
  have h_x : digits b (karatsuba_n1 x b m) < n := by
    -- Apply the lemma karatsuba_step_bound_z2' to x.
    apply karatsuba_step_bound_z2' b n m x hb (by
    exact le_max_left _ _) (by
    grind +ring);
    rfl
  have h_y : digits b (karatsuba_n1 y b m) < n := by
    apply karatsuba_step_bound_z2' b n m y hb (by
    exact le_max_right _ _) (by
    grind);
    rfl
  exact max_lt h_x h_y); (
  -- Apply the lemma that states the digits of the sum of the high and low parts is less than n.
  have h_sum_digits : ∀ z : ℤ, digits b z ≤ n → digits b (karatsuba_n1 z b m + karatsuba_n0 z b m) < n := by
    intro z hz; exact karatsuba_step_bound_z3' b n m z hb hz (by
    -- Since the maximum of two numbers is not less than or equal to 4, it must be greater than 4.
    apply lt_of_not_ge; exact ‹¬Max.max (digits b x) (digits b y) ≤ 4›) rfl;
  exact max_lt ( h_sum_digits x ( le_max_left _ _ ) ) ( h_sum_digits y ( le_max_right _ _ ) ))

theorem karatsuba_correctness (x y : ℤ) (b : ℕ) (hb : 1 < b)
: karatsuba x y b hb = x * y
:= by
  -- We'll use induction on the maximum number of digits of x and y.
  induction' n : max (digits b x) (digits b y) using Nat.strong_induction_on with n ih generalizing x y b hb;
  unfold karatsuba;
  split_ifs <;> simp_all +decide [mul_comm];
  rw [ ih _ _ _ _ _ _ rfl, ih _ _ _ _ _ _ rfl, ih _ _ _ _ _ _ rfl ];
  · rw [ ← n ] ; ring;
    rw [ show karatsuba_n1 x b ( ( 1 + Max.max ( digits b x ) ( digits b y ) ) / 2 ) = x / b ^ ( ( 1 + Max.max ( digits b x ) ( digits b y ) ) / 2 ) by rfl, show karatsuba_n0 x b ( ( 1 + Max.max ( digits b x ) ( digits b y ) ) / 2 ) = x % b ^ ( ( 1 + Max.max ( digits b x ) ( digits b y ) ) / 2 ) by rfl, show karatsuba_n1 y b ( ( 1 + Max.max ( digits b x ) ( digits b y ) ) / 2 ) = y / b ^ ( ( 1 + Max.max ( digits b x ) ( digits b y ) ) / 2 ) by rfl, show karatsuba_n0 y b ( ( 1 + Max.max ( digits b x ) ( digits b y ) ) / 2 ) = y % b ^ ( ( 1 + Max.max ( digits b x ) ( digits b y ) ) / 2 ) by rfl ] ; rw [ Int.emod_def, Int.emod_def ] ; ring;
  · apply_rules [ max_lt, karatsuba_step_bound_z0' ];
  · have h_sum_digits : ∀ z : ℤ, digits b z ≤ Nat.max (digits b x) (digits b y) → digits b (karatsuba_n1 z b ((Nat.max (digits b x) (digits b y) + 1) / 2) + karatsuba_n0 z b ((Nat.max (digits b x) (digits b y) + 1) / 2)) < Nat.max (digits b x) (digits b y) := by
      intros z hz
      apply karatsuba_step_bound_z3' b (Nat.max (digits b x) (digits b y)) ((Nat.max (digits b x) (digits b y) + 1) / 2) z hb hz (by linarith) rfl;
    exact max_lt ( by simpa only [ ← n ] using h_sum_digits x ( le_max_left _ _ ) ) ( by simpa only [ ← n ] using h_sum_digits y ( le_max_right _ _ ) );
  · refine' max_lt _ _;
    · apply karatsuba_step_bound_z2' b _ _ _ hb (by linarith [le_max_left (digits b x) (digits b y)]) (by linarith [le_max_left (digits b x) (digits b y)]) rfl;
    · apply karatsuba_step_bound_z2' b _ _ _ hb (by linarith [le_max_right (digits b x) (digits b y)]) (by linarith [le_max_right (digits b x) (digits b y)]) rfl
